# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[general]
import = [
	"~/.config/alacritty/theme/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }

[cursor]
style = { shape = "Block", blinking = "On" }

